swagger: "2.0"
info:
  description: "Banka is a light-weight core banking application that powers banking operations like account creation, customer deposit and withdrawals. This app is meant to support a single bank, where users can signup and create bank accounts online, but must visit the branch to withdraw or deposit money."
  version: "1.0.0"
  title: "Banka"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "kech3443@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "kechyy-banka-app.herokuapp.com"
basePath: "/api/v1"
tags:
- name: "users"
  description: "user api"
- name: "account"
  description: "account api"
- name: "transactions"
  description: "transaction api"
schemes:
- "https"
- "http"
paths:
  /user/auth/signup:
    post:
      tags:
      - "users"
      summary: "Add a new user to the database"
      description: "Add a new user to the database"
      operationId: "signupUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "user object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/signupUser"
      responses:
        201:
          description: "Successful signup"
        409:
          description: "Email exists"
        400:
          description: "Bad request"
  /user/auth/signin:
    post:
      tags:
      - "users"
      summary: "Add a new user to the database"
      description: "Signin user"
      operationId: "signinUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "user object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/signinUser"
      responses:
        200:
          description: "Successful signin"
        400:
          description: "signin Error"
  /user/profile:
    get:
      tags:
      - "users"
      summary: "View user profile"
      description: "User profile"
      operationId: "userProfile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "email"
        description: "Email that is needed to fetch the a specific user profile details"
        required: true
        type: "string"
        schema:
          $ref: "#/definitions/userProfile"
      responses:
        200:
          description: "Successful profile operation"
        404:
          description: "No Record Found"
  /user/account:
    post:
      tags:
      - "users"
      summary: "Creates a new bank account"
      description: ""
      operationId: "createAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "Bank account object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/createAccount"
      responses:
        201:
          description: "Successful account creation"
        400:
          description: "Bad Request"
  /accounts/:accountNumber/transactions:
    get:
      tags:
      - "users"
      summary: "Finds user transactions by account number on a specific accoun"
      description: "User account numbers are fetch from  created accounts"
      operationId: "accountTransactionHistories"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "accountNumber"
        description: "Bank account number that is needed to find a user account transaction history"
        required: true
        type: "integer"
        schema:
          $ref: "#/definitions/accountTransactionHistory"
      responses:
        200:
          description: "Successful transaction operation"
        404:
          description: "No Record Found"
  /transactions/:transactionId:
    get:
      tags:
      - "users"
      summary: "Finds user's specific transactions by transaction id"
      description: "Transaction Id is passed on the route path as parameter"
      operationId: "specificAccountTransaction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "transactionId"
        description: "Bank transaction Id that is needed to find user account transaction history"
        required: true
        type: "integer"
        schema:
          $ref: "#/definitions/specificAccountTransaction"
      responses:
        200:
          description: "Successful transaction operation"
        404:
          description: "No Record Found"
  /accounts/:accountNumber:
    get:
      tags:
      - "users"
      summary: "Finds user's account details by account number"
      description: "Account number is passed on the route path as parameter"
      operationId: "specificAccountDetails"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "accountNumber"
        description: "Bank account number that is needed to find user account details"
        required: true
        type: "integer"
        schema:
          $ref: "#/definitions/specificAccountDetails"
      responses:
        200:
          description: "Successful transaction operation"
        404:
          description: "No Record Found"
  /auth/createUser:
    post:
      tags:
      - "admin"
      summary: "Creates new user"
      description: "User Account"
      operationId: "newUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "admin"
        description: "New user object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/newUser"
      responses:
        201:
          description: "Successful user creation"
        400:
          description: "Bad Request"
        409:
          description: "User already exist"  
definitions:
  signupUser:
    type: "object"
    required:
      - firstName
      - lastName
      - email
      - password
      - cpassword
    properties:
      firstName:
        type: "string"
        uniqueItems: false
      lastName:
        type: "string"
        uniqueItems: false
      email:
        type: "string"
        uniqueItems: true
      password:
        type: "string"
        uniqueItems: false
      cpassword:
        type: "string"
        uniqueItems: false
  signinUser:
    type: "object"
    required:
      - email
      - password
    properties:
      email:
        type: "string"
        uniqueItems: true
      password:
        type: "string"
        uniqueItems: true
  userBankAccount:
    type: "object"
    required:
      - email
    properties:
      email:
        type: "string"
        uniqueItems: true
      userid:
        type: "integer"
        uniqueItems: false  
  newUser:
    type: "object"
    required:
      - firstName
      - lastName
      - email
      - usertype
    properties:
      firstName:
        type: "string"
        uniqueItems: false
      lastName:
        type: "string"
        uniqueItems: false
      email:
        type: "string"
        uniqueItems: true
      usertype:
        type: "string"
        uniqueItems: false
        